### ISSUE TITLE
That is the log of the 500 error null when calling the gateway 2 times (I only pasted the part of the error, not the complete log)

### ISSUE THREAD

**Issue by perezdf** [coatrack/coatrack#12]
That is the log of the 500 error null when calling the gateway 2 times (I only pasted the part of the error, not the complete log)

2020-04-03 17:05:19.211 DEBUG 16140 --- [nio-8088-exec-2] w.c.HttpSessionSecurityContextRepository : SecurityContext 'org.springframework.security.core.context.SecurityContextImpl@1f: Authentication: eu.iof2020.ygg.proxy.security.ApiKeyAuthToken@1f: Principal: 0ea6d60c-33a0-41d6-b426-4af4f2aa88bf; Credentials: [PROTECTED]; Authenticated: false; Details: null; Not granted any authorities' stored to HttpSession: 'org.apache.catalina.session.StandardSessionFacade@252ad211
2020-04-03 17:05:19.219 ERROR 16140 --- [pool-2-thread-1] e.i.y.proxy.metrics.MetricsTransmitter   : Exception when communicating with YGG admin server
org.springframework.web.client.HttpServerErrorException: 500 null
        at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:88) ~[spring-web-4.3.13.RELEASE.jar!/:4.3.13.RELEASE]
        at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:707) ~[spring-web-4.3.13.RELEASE.jar!/:4.3.13.RELEASE]
        at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:660) ~[spring-web-4.3.13.RELEASE.jar!/:4.3.13.RELEASE]
        at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:635) ~[spring-web-4.3.13.RELEASE.jar!/:4.3.13.RELEASE]
        at org.springframework.web.client.RestTemplate.postForObject(RestTemplate.java:405) ~[spring-web-4.3.13.RELEASE.jar!/:4.3.13.RELEASE]
        at eu.iof2020.ygg.proxy.metrics.MetricsTransmitter.transmitToYggAdmin(MetricsTransmitter.java:108) [classes!/:0.5.0-2020W14]
        at eu.iof2020.ygg.proxy.metrics.MetricsTransmitter.set(MetricsTransmitter.java:95) [classes!/:0.5.0-2020W14]
        at org.springframework.boot.actuate.metrics.export.MetricCopyExporter.write(MetricCopyExporter.java:134) [spring-boot-actuator-1.5.9.RELEASE.jar!/:1.5.9.RELEASE]
        at org.springframework.boot.actuate.metrics.export.AbstractMetricExporter.exportGroups(AbstractMetricExporter.java:116) [spring-boot-actuator-1.5.9.RELEASE.jar!/:1.5.9.RELEASE]
        at org.springframework.boot.actuate.metrics.export.AbstractMetricExporter.export(AbstractMetricExporter.java:92) [spring-boot-actuator-1.5.9.RELEASE.jar!/:1.5.9.RELEASE]
        at org.springframework.boot.actuate.metrics.export.MetricExporters$ExportRunner.run(MetricExporters.java:129) [spring-boot-actuator-1.5.9.RELEASE.jar!/:1.5.9.RELEASE]
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-4.3.13.RELEASE.jar!/:4.3.13.RELEASE]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [na:1.8.0_241]
        at java.util.concurrent.FutureTask.runAndReset(Unknown Source) [na:1.8.0_241]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(Unknown Source) [na:1.8.0_241]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [na:1.8.0_241]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [na:1.8.0_241]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [na:1.8.0_241]
        at java.lang.Thread.run(Unknown Source) [na:1.8.0_241]
2020-04-03 17:05:19.227 DEBUG 16140 --- [nio-8088-exec-2] s.s.w.c.SecurityContextPersistenceFilter : SecurityContextHolder now cleared, as request processing completed
2020-04-03 17:05:19.248 E

**Comment by gr-hovest-atb** [comment]
This issue is related to a specific coatrack installation, not to the general source code, so it is not relevant for this repository.
