### ISSUE TITLE
When registering a new user, getting user info from Github fails 

### ISSUE THREAD

**Issue by gr-hovest-atb** [coatrack/coatrack#135]
This occurred during local development testing:

- when logging in as a user who is already "registered" (via test data by "database initializer"), it works fine
- when logging in as another user, who is not yet registered, an error occurs (can be tested e.g. by running admin application with the "default ygg-admin" profile)

Screenshot:
![image](https://user-images.githubusercontent.com/6480551/128154000-850aca38-4ef4-4e77-947b-33701f8ab5b4.png)

The Log says:
```
org.springframework.web.client.HttpClientErrorException: 400 Bad Request
	at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:85) ~[spring-web-4.3.13.RELEASE.jar!/:4.3.13.RELEASE]
	at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:707) ~[spring-web-4.3.13.RELEASE.jar!/:4.3.13.RELEASE]
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:660) ~[spring-web-4.3.13.RELEASE.jar!/:4.3.13.RELEASE]
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:620) ~[spring-web-4.3.13.RELEASE.jar!/:4.3.13.RELEASE]
	at org.springframework.web.client.RestTemplate.getForObject(RestTemplate.java:294) ~[spring-web-4.3.13.RELEASE.jar!/:4.3.13.RELEASE]
	at eu.coatrack.admin.controllers.AdminController.home(AdminController.java:217) ~[classes!/:2.0.0-SNAPSHOT]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_292]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_292]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_292]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_292]
```
Looking at the related position in the code, in `AdminController.java:217`, the "Bad Request" happens when getting user information from Github:
```
 String userInfo = restTemplate.getForObject(GITHUB_API_USER + "?access_token=" + details.getTokenValue(), String.class);
```
Assumption: the access token should not be passed as query parameter any more, but in the header, see also the (probably) related issue #121

**Comment by BrunoSilvaATB** [comment]
I think that #138 also solve this issue

**Comment by perezdf** [comment]
yes, #138 fixed that issue

**Comment by gr-hovest-atb** [comment]
Duplicate of #41
