### ISSUE TITLE
Gateway console shows BadCredentialsException although API key is valid

### ISSUE THREAD

**Issue by gr-hovest-atb** [coatrack/coatrack#47]
Even if a valid API key is used and the call is successfully forwarded by the gateway, there is a `BadCredentialsException` showing up in the gateway console, as if there was an invalid API key.

When actually using an invalid key, that exception is displayed twice in the console, so it it seems like the ApiKeyAuthTokenVerifier is always running twice, and at least one run always fails.

Exception is:

> 2020-10-19 12:39:32.051 DEBUG 33564 --- [nio-8088-exec-5] e.c.p.security.ApiKeyAuthTokenVerifier   : API key parameter missing or invalid: [Assertion failed] - this argument is required; it must not be null
> 2020-10-19 12:39:32.053 DEBUG 33564 --- [nio-8088-exec-5] o.s.s.w.a.ExceptionTranslationFilter     : Authentication exception occurred; redirecting to authentication entry point
> 
> org.springframework.security.authentication.BadCredentialsException: API key parameter missing or invalid: [Assertion failed] - this argument is required; it must not be null
> 	at eu.coatrack.proxy.security.ApiKeyAuthTokenVerifier.authenticate(ApiKeyAuthTokenVerifier.java:120) ~[classes!/:1.2.0]
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_265]
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_265]
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_265]
> 	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_265]
> 	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:333) ~[spring-aop-4.3.13.RELEASE.jar!/:4.3.13.RELEASE]
> 	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:207) ~[spring-aop-4.3.13.RELEASE.jar!/:4.3.13.RELEASE]
> 	at com.sun.proxy.$Proxy91.authenticate(Unknown Source) ~[na:na]
> 	at org.springframework.security.authentication.ProviderManager.authenticate(ProviderManager.java:199) ~[spring-security-core-4.2.3.RELEASE.jar!/:4.2.3.RELEASE]
> 	at org.springframework.security.access.intercept.AbstractSecurityInterceptor.authenticateIfRequired(AbstractSecurityInterceptor.java:354) ~[spring-security-core-4.2.3.RELEASE.jar!/:4.2.3.RELEASE]
>

**Comment by BrunoSilvaATB** [comment]
@gr-hovest-atb I checked where the requests are coming from, and the first one is correct (http://localhost:8088/gateway-issue-testing), however the second time it gets a request from(http://localhost:8088/favicon.ico)

![image](https://user-images.githubusercontent.com/47450617/101895389-c4aa3b80-3ba7-11eb-84f3-80a7281fccf3.png)

**Comment by gr-hovest-atb** [comment]
Just tested this again in different settings: the exception does _not_ occur when calling via cURL or Postman, it only occurs when testing access to the gateway using a web browser. The reason is obviously that the browser always asks for the site's favicon without adding an api key URL parameter. 

This means that this is not a bug, but an expected behavior. It is just a little bit annoying when testing access using a web browser.
